CREATE TABLE IF NOT EXISTS `Users` (
    `id` INT NOT NULL AUTO_INCREMENT
    ,`email` VARCHAR(100) NOT NULL
    ,`password` VARCHAR(60) NOT NULL
    ,`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ,`fname` VARCHAR(60) NOT NULL
    ,`lname` VARCHAR(60) NOT NULL
    , `public` TINYINT(1) DEFAULT 1
    ,PRIMARY KEY (`id`)
    ,UNIQUE (`email`)
) 